### ISSUE TITLE
Investigate Pretty Print Source

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#100]
**User Story**

As a developer who is using minified source code I want to be able to convert the code into a pretty print version such that I can more easily read and understand the code.

**Notes**

Firefox replaces the current source code with the pretty printed version so an improved interaction like how Chrome creates a new source filed `x.js:formatted` isn't in scope just yet.

**UX needs**

- Location of toggle button
- Progress bar? (do we need a progress bar for when conversion takes a while)
  - Currently Firefox blocks access to the existing source code, this is an interaction we probably want to avoid

- [ ] Button to toggle pretty print
    Swaps out the current editor code with formatted version.

**Comment by jasonLaster** [comment]
I don't think we will get to this pre-london, so closing for now. Feel free to open when you're ready to work on it.
