### ISSUE TITLE
Simple variable scope list

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#102]
**User Story**

As a web developer who is stepping through their code I want to see the available variables and current scopes involved in the page such that I can inspect the values of my variables and be aware if any of them are hoisted out of my expected scope.

- [x] List of scopes
    On the right hand side, under the breakpoint list.

    

- [x] List of variables within scopes
    Variables are listed inside the&nbsp;accordion under the scopes.

**Comment by clarkbw** [comment]
#118 handled this, there's a bit more work that could be done to style it but we've satisfied the simple implementation for now.

**Comment by jasonLaster** [comment]
Lets call it done and add more polish tickets. @clarkbw, would you have time to play with it and create some polish tickets for this week or next sprint.

**Comment by clarkbw** [comment]
> would you have time to play with it and create some polish tickets for this week or next sprint

Definitely!  I'll take a look at it later today and file some tickets.
