### ISSUE TITLE
Investigate Tree View Component

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#103]
Investigate and review the various Tree View components available as modules compared to the internal Firefox Tree View module available. &nbsp;This module will be the basis for the Source Code Tree View.

**Comment by TatumCreative** [comment]
For my reference, existing Firefox Tree View components:
fitzgen's: https://github.com/mozilla/gecko-dev/blob/master/devtools/client/shared/components/tree.js
honza's: https://github.com/mozilla/gecko-dev/tree/master/devtools/client/shared/components/tree

**Comment by clarkbw** [comment]
@TatumCreative make sure to take a look at the comments by @markerikson in https://github.com/jlongster/debugger.html/issues/104#issuecomment-216732509

**Comment by jlongster** [comment]
Let's merge this with #104. We've done the investigation, now we just need to tie it back to the sources view.

@TatumCreative I'll ping you tomorrow because I should have a basic sources tree working with Nick's tree view then. We should compare notes.
