### ISSUE TITLE
Nested Accordions

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#126]
Because of how the CSS is setup when the parent pane is open, it's children will be as well.

I'm not sure if this is something we should prioritize. Also, I'm not sure if the accordion ui makes sense for scopes.

![nested accordions](https://cloud.githubusercontent.com/assets/254562/14958219/a4c30a34-1057-11e6-9dca-6b7e4a35b458.png)

**Comment by jlongster** [comment]
I think when we get the tree view we'll use a tree view instead. Each scope will be a top-level entry.

**Comment by clarkbw** [comment]
Just to note that #132 is related to this for showing the scope property values.
And #103 is the higher level tree view component investigation

**Comment by jasonLaster** [comment]
sgtm

**Comment by jasonLaster** [comment]
we'll use the tree
