### ISSUE TITLE
Add hot reloading

### ISSUE THREAD

**Issue by jlongster** [jlongster/debugger.html#127]
We're at the point where hot reloading would be super useful, because you can develop with a bunch of state already built up. I know storybooks are another way to do this, but we should be able to hot reload the main app as well. I'm working on hooking it up.

**Comment by jlongster** [comment]
The hot reloading story of React today is a little shaky. A new version of react-hot-loader is being worked on but it's not stable enough yet. We could use the old version, but it doesn't support functional components.

It also involves more boilerplate setup code. I'd love to get this working, but it just doesn't seem stable enough yet. My code got it working, but components seemed to lose local state (making a change to the accordion would make it lose state and collapse, while it should preserve state).

Here's a starting point if anyone picks this up in the future: https://github.com/jlongster/debugger.html/tree/hot-reloading

**Comment by jasonLaster** [comment]
@jlongster do you think we can do this pre-london? 

I think it's a nice polish piece for our infrastructure.
