### ISSUE TITLE
Show Breakpoint "Snippets"

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#133]
We're currently ignoring showing breakpoint snippets. We should try and show them with the same logic used in the current debugger.

![screen shot 2016-05-02 at 6 33 29 pm](https://cloud.githubusercontent.com/assets/254562/14970061/19517d7c-1094-11e6-8ed5-7b060bc4a585.png)

**Comment by clarkbw** [comment]
The previous text logic is here: https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/content/actions/breakpoints.js#69 but needs to be adapted.

**Comment by jasonLaster** [comment]
done
