### ISSUE TITLE
Style source files in the Sources list

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#136]
The images for source files and domains seems like it isn't lined up vertically with the text.
Likely a `vertical-align: middle` is what we need.
![screen shot 2016-05-03 at 9 14 50 am](https://cloud.githubusercontent.com/assets/2134/14990035/991fdc30-110f-11e6-81e6-49d5b5ff5d75.png)

Also, source files are sometimes bumped to the next line. We'll likely want to do a text-overflow elippsis

<img width="488" alt="10eeef39-cce1-49c1-9faa-9d6cdd212903" src="https://cloud.githubusercontent.com/assets/254562/15017797/23e429cc-11e5-11e6-85fb-501cb060848e.png">

**Comment by jlongster** [comment]
Closing this as we have a tree view now and I think the styling is good enough for a demo, and there are more important things to do. I'm going to file some bugs for the tree view behavior that a beginner could do if they want.
