### ISSUE TITLE
Editor scrolling relies on scrollBy

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#145]
Chrome scrollling was temporarily broken due to not supporting `scrollBy`.

This commit fixed it, https://github.com/jlongster/debugger.html/commit/9164c084f64a3e12f126b6a608772e801a2e784e, but opens the question of whether we want to use an API that only works in firefox.

Moreover, when i tested the editor scrolling with the trackpad in `jquery.js` i could not find a slow down, which the @gabrielluong bug was solving.

**Comment by jlongster** [comment]
Yeah, this is worth looking at again. I've noticed the gutter problem before, but we may be prematurely fixing it. By the time we launch the debugger it may be fixed. Anyway, I'm fine keeping the code in editor.js there, but for now maybe we should disable the 1-line in the editor component that calls it.

**Comment by gabrielluong** [comment]
The behaviour we added in 9164c08 is really only relevant for firefox because of APZ. We should really only have a check if the browser is firefox when adding scrollBy.

**Comment by jasonLaster** [comment]
Sounds good @gabrielluong.

We could probably add an `isFirefox` function in `configs/feature.js`

```js
function isFirefox() {
  return /firefox/i.test(navigator.userAgent)
}
```
