### ISSUE TITLE
Demo of a build in Firefox

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#153]
&nbsp;The focus of this issue is only to create a demo worthy bundle of debugger.html that works within Firefox for the London work week. &nbsp;There are several issues related to releasing the debugger.html project in Firefox most of which this issue is not focused on.

- [ ] Pausing / Resuming

- [ ] Step over, in, out

- [ ] Breakpoints (creating / removing)

- [ ] Breakpoint listing (toggling)

- [ ] Pausing on breakpoints

- [ ] Working Source Tree View

- [ ] Scope listing (variables within scopes)

- [ ] Call Stacks (with frame navigation)

**Comment by jlongster** [comment]
I created a new tool and threw the js and css bundles in there, and it partially works! I did have to rework our `main.js` entry point to allow this toolbox to install the RDP connection that it already has, but that wasn't too bad. I'll create a PR for that next week.

There are also some weird issues about the old debugger catching events (like paused, etc).

But it *looks* pretty good!

<img width="1077" alt="screen shot 2016-05-13 at 4 46 15 pm" src="https://cloud.githubusercontent.com/assets/17031/15261675/d7ed65bc-192b-11e6-995e-b649c61ae689.png">

**Comment by jasonLaster** [comment]
I'd say so. Looks really nice in its natural home.

**Comment by jasonLaster** [comment]
It would be nice to have a pref that shows the new html version over the old version.

**Comment by jlongster** [comment]
I have a pretty solid demo working, see the screenshot in this PR: https://github.com/jlongster/debugger.html/pull/238#issuecomment-223671827
