### ISSUE TITLE
More generic application state

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#154]
With multiple platform targets as a primary goal we need to review how our debugger handles application state which has likely become very Firefox specific. &nbsp;We should focus this refactor of our current application state on the planned platform targets.

This covers applications state such as:

- Breakpoints
- Pause
- Resume
- Source Text
- Tab List

Planned platform targets:

- Firefox (&nbsp; [https://wiki.mozilla.org/Remote\_Debugging\_Protocol](https://wiki.mozilla.org/Remote_Debugging_Protocol)&nbsp;)
- Node.js (&nbsp; [https://nodejs.org/api/debugger.html](https://nodejs.org/api/debugger.html)&nbsp;)
- Chrome RDP (&nbsp; [http://chromedevtools.github.io/debugger-protocol-viewer-1.1/Debugger/](http://chromedevtools.github.io/debugger-protocol-viewer-1.1/Debugger/)&nbsp;)

**Comment by clarkbw** [comment]
Might also be useful to take a look at http://remotedebug.org/ / https://github.com/RemoteDebug for existing information already gathered on a more generic debug state.

**Comment by jasonLaster** [comment]
I believe we said this is done and the investigate node bug would be our next item.
