### ISSUE TITLE
Investigate connecting to Node

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#155]
Investigate a demo of debugger.html connecting to Node.js over the Node remote debug protocol. &nbsp;This investigation should also include running&nbsp;within the Electron framework to provide a viewer and target for shipping.

Similar projects:

- [https://github.com/Jam3/devtool](https://github.com/Jam3/devtool)

**Comment by jlongster** [comment]
Jason, although this is assigned to me, feel free to explore this area too. I got node connecting last December and I have some ideas about it, but you'll be working on Chrome which is similar work, so feel free to work on this too. Let's talk next week about it.

**Comment by jlongster** [comment]
This is done in https://github.com/jlongster/debugger.html/pull/236

**Comment by andreicristianpetcu** [comment]
for posterity I fixed the link to the issue https://github.com/firefox-devtools/debugger/pull/236
