### ISSUE TITLE
Create a standalone application

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#156]
It would be nice to demo the debugger as a standalone electron app. This would be very easy to do if we publish debugger.html as an npm package.

- [ ] create a debugger.html npm package
- [ ] add a `bin` script for starting the dev-server or add a publish script for bundling.
- [ ] version debugger.html `0.0.1`
- [ ] use the debugger.html index

**Comment by jlongster** [comment]
Are you planning on doing this in this sprint? This isn't technically part of this sprint, and I think it's more important to start working on making the app state more generic so we can connect to chrome/node (#154).

**Comment by jasonLaster** [comment]
That's a good point. I'll probably sandbox it at an hour as an experiment.

**Comment by jlongster** [comment]
Cool, that's totally fine, just wanted to get it in aha if you were going to work on it!

**Comment by jasonLaster** [comment]
did an initial prototype. 

<img width="793" alt="screen shot 2016-05-20 at 7 39 44 pm" src="https://cloud.githubusercontent.com/assets/254562/15444767/5df80a54-1ec2-11e6-9beb-99b43f82edfb.png">

Turned out to be pretty simple

**Comment by jasonLaster** [comment]
The Electron App lives here:
https://github.com/jasonLaster/debugger.html.app

It uses a new Debugger.html npm package
https://www.npmjs.com/package/debugger.html

It works by spinning up local server that serves the bundle.js and styles.js. 

It's currently missing the svgs
