### ISSUE TITLE
Add File Search modal

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#158]
Add a file search modal that opens on cmd+p, and finds files with fuzzy search.

<img width="520" alt="screen shot 2016-05-13 at 9 01 24 am" src="https://cloud.githubusercontent.com/assets/254562/15253866/f7580ca6-18e8-11e6-8679-90413d3fc09a.png">

- [ ] use a modal (it might make sense to borrow one from the community)
- [ ] use a fuzzy search algorithm [1]
- [ ] on select jump to file
- [ ] up / down navigation 

[1]
chrome: 
    [filepathscore](https://code.google.com/p/chromium/codesearch#search/&q=filepathscore&sq=package:chromium&type=cs)  
https://github.com/atom/fuzzy-finder
https://github.com/lingo/sublime-fscompletion
https://github.com/sagold/FuzzyFilePath
https://github.com/atom/fuzzaldrin

**Comment by jasonLaster** [comment]
@gabrielluong will take a stab at this

**Comment by jlongster** [comment]
Nice! This would be great to have early on.

**Comment by jasonLaster** [comment]
@helenvholmes mind adding some of your designs here. Specifically the file search design

**Comment by helenvholmes** [comment]
Here were the designs we worked on on Tuesday:

<img width="851" alt="screen shot 2016-05-26 at 4 35 23 pm" src="https://cloud.githubusercontent.com/assets/1720093/15589218/e22e3f90-235f-11e6-917d-b91af710dbb4.png">

**Comment by amitzur** [comment]
Good thing I went over the list of issues, since this was the first enhancement issue I was about to file.
It's really the first thing you need when starting to debug since there are so many files in an average project.

I'm wondering - what's the reason to replace the editor rather than open a modal?

**Comment by helenvholmes** [comment]
As users can't interact with the editor and the modal at the same time, a modal is in essence interrupting the editor entirely—replacing it entirely for this interaction doesn't seem particularly foreign.

**Comment by jasonLaster** [comment]
@helenvholmes ^

This is as fairly large issue, but couldn't be split up nicely if you're interested in taking a stab. E.g. Fuzzy search can come later. 

I think replacing the editor was suggested as it's cleaner. I'd be open to trying a modal. 

Three use cases are searching files, functions, text. Full project search might make sense either way. I like how many projects show results in the editor with a new tab

**Comment by jasonLaster** [comment]
* could be broken up. (Stupid mobile input)

**Comment by helenvholmes** [comment]
I agree, replacing the editor is cleaner.

Since we've gone back and forth on these designs in-person, let's move forward with these and not implement a modal unless it proves necessary in the future.

**Comment by jasonLaster** [comment]
#310 Adds a V1 version
