### ISSUE TITLE
Investigate reselect

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#16]
We currently have simple state query functions in queries.js. Lets investigate, [reselect](https://github.com/reactjs/reselect), which should help us clean up the way we access the state.

**Comment by jlongster** [comment]
@jasonLaster As far as I know we can close this issue, right? If we need it later we can convert queries to it without much work. For now it sounds like we're going to keep doing what we already have.

**Comment by jasonLaster** [comment]
That's true.
