### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#162]
The docs should have steps for running the tests, linting, ...

**Comment by jasonLaster** [comment]
Lets also include a screenshot of what the debugger with local tabs looks like

![screen shot 2016-05-16 at 11 02 03 am](https://cloud.githubusercontent.com/assets/254562/15293339/8522dd36-1b55-11e6-9b92-a22ea1da6a83.png)

**Comment by jasonLaster** [comment]
I'll PR this commit https://github.com/jlongster/debugger.html/commit/0f272d97e439a51578306be296f79a85694a1024 after the integration tests land, as it's dependent on that work.

**Comment by jlongster** [comment]
Yeah, I've been thinking about this too, good work. Please don't use Chrome in the screenshot!

**Comment by jasonLaster** [comment]
![screen shot 2016-05-16 at 1 24 29 pm](https://cloud.githubusercontent.com/assets/254562/15297643/34575ca6-1b69-11e6-9703-8ba0a029d4f9.png)

**Comment by jasonLaster** [comment]
done
