### ISSUE TITLE
Remove development.local warning

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#163]
Currently there is a warning:

![](https://irccloud.mozilla.com/file/dBafCneU/)

because there's a require for a file that does not exist:
https://github.com/jlongster/debugger.html/blob/master/public/js/configs/feature.js#L9-L13

We should first check if the file exists and then require the file instead of the try/catch

**Comment by TatumCreative** [comment]
There's no `fs` module here for checking the existence of files. I'm not sure there is an easy fix for this. The only thing I can figure out is creating a separate npm run script for local development options using environment variables.

**Comment by jasonLaster** [comment]
@TatumCreative What do you mean by `npm run script`?

We might need to do something with webpack or the development server.

**Comment by TatumCreative** [comment]
@jasonLaster I'm referring to https://github.com/jlongster/debugger.html/blob/master/package.json#L4-L14 for an npm run script.

**Comment by jasonLaster** [comment]
@TatumCreative I'd like to have the options bunded, but this should be possible. with webpack

**Comment by jasonLaster** [comment]
Removed development.local
