### ISSUE TITLE
Add Redux Devtools

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#166]
It'd be helpful to have a development tool for seeing the redux action history. This will help newbies see what is happening and hopefully help us replay actions as well.

**Comment by jasonLaster** [comment]
There's a chrome extension. we can also have a docked app logger (in development mode)

**Comment by TatumCreative** [comment]
Here are the blockers for the Redux DevTools Extension in Firefox:

https://github.com/zalmoxisus/redux-devtools-extension/issues/9

**Comment by jlongster** [comment]
There are various "monitors" and some of them are really slow. I'd like one that just does rich console.logging, but the overlay is nice too. It would be nice if we could customize which devtools to use in the config or something.

**Comment by clarkbw** [comment]
There is a work in progress here #333
