### ISSUE TITLE
Scopes/Variables viewer

### ISSUE THREAD

**Issue by jlongster** [jlongster/debugger.html#168]
We're doing pretty good this sprint, so I'm going to spend a little time seeing what it looks like to apply the tree to the scopes pane. A lot of other people need this and we need to figure out the story with the tree component (across other tools). Won't spend too much time on it, but I think I can replace the accordion with the tree view without too much work.

**Comment by jlongster** [comment]
I'm pretty confident that this is going to come together nicely. We're in a good place now with an existing client to fetch the properties, a tree view to view them, and the reps components to format values. Got this far today, will probably spend another half day or so on it and then work on the Firefox bundle again.

<img width="266" alt="screen shot 2016-05-17 at 5 52 06 pm" src="https://cloud.githubusercontent.com/assets/17031/15340594/2747bd86-1c58-11e6-8175-0eb1366964af.png">

**Comment by jasonLaster** [comment]
nice!

**Comment by clarkbw** [comment]
I believe this was done in #178
