### ISSUE TITLE
Lint for `displayName`

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#170]
react components should have a displayName. Our eslint rules should show a warning for that, but they currently don't.

**Comment by clarkbw** [comment]
We already have a rule in the [.eslintrc](https://github.com/jlongster/debugger.html/blob/master/.eslintrc#L51) file 

We need someone to investigate if the rule is still accurate and / or why it isn't showing a warning.

Once fixed you can either file a new issue for any errors that appear or fix those errors in a separate commit.

**Comment by jlongster** [comment]
fixed in https://github.com/jlongster/debugger.html/commit/93a7cde13783359917d752d7e4913f5034b5437a
