### ISSUE TITLE
Consider removing todomvc nodemodule dependency

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#171]
Currently, we depend on todomvc module for integration tests. We also have a node_modules test-server endpoint for resolving these resources. 

We should decide if
a) we want to lock todomvc's dependency
b) replace it with static files
c) remove todomvc tests entirely

**Comment by jlongster** [comment]
I vote that we just add the static files. It just seems less subject to change.

**Comment by jasonLaster** [comment]
I'd vote for pinning the node_module version. It's basically the same thing, but not committed. I don't care that much though.

**Comment by jlongster** [comment]
I wouldn't be surprised if we want to change the page at some point to make it easier to write a specific test. I guess I don't care that much right now, but I predict that we will want to do it in the future :)

**Comment by jasonLaster** [comment]
That makes sense. I'll probably feel differently when we have other test files too.

**Comment by jasonLaster** [comment]
was removed
