### ISSUE TITLE
Polish Source Tree

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#174]
- [ ] icons
- [ ] selected file UI
- [ ] layout (height, ...)

**Comment by jlongster** [comment]
This is a little vague. I'm assuming by "selected file UI" you mean the bug where the full text isn't highlighted if it's wider then the container? Can we explain that here in detail? And I'm not sure it's worth having the 3rd item "layout". That's pretty subjective and we'll do whatever Helen designs. I think it's fine for now.

Also, fwiw I'd rather focus on the feature in https://github.com/jlongster/debugger.html/issues/160 first before any of this.

**Comment by TatumCreative** [comment]
Sounds good to me, I'll work on #160 first.

**Comment by helenvholmes** [comment]
I'm going to close this based on #197 + #86.
