### ISSUE TITLE
Editor chopped off at the bottom

### ISSUE THREAD

**Issue by helenvholmes** [jlongster/debugger.html#191]
I'm noticing that the bottom of the editor gets lopped off: 

<img width="1279" alt="image 2016-05-23 at 10 51 13 am" src="https://cloud.githubusercontent.com/assets/1720093/15475049/d2490948-20d5-11e6-9e5d-bb4705682aab.png">

**Comment by helenvholmes** [comment]
I'm no longer able to replicate this. Is anyone else seeing this issue?

**Comment by jlongster** [comment]
I haven't been able to repro either.

**Comment by helenvholmes** [comment]
My original screenshot wasn't very clear anyway—I'll close this, we'll reopen if someone's able to replicate.
