### ISSUE TITLE
Slow loading on very large files

### ISSUE THREAD

**Issue by helenvholmes** [jlongster/debugger.html#193]
@jlongster mentioned that this might be related to websockets and that it might be solved with a TCP mode for certain situations.

The current Firefox debugger is optimized for very large files, such as the [12mb file in bgrins' debugger demo](http://bgrins.github.io/devtools-demos/debugger/scripts.html).

There seems to be some lag in the debugger.html to load the source into the editor (the jump is something like a 500ms wait in the Firefox debugger to a 5s wait in the debugger.html project, although that's very much a guesstimation).

**Comment by jlongster** [comment]
I think the majority of the slow-down is the logging in the proxy server. It logs all messages to and from the debugger server, so it logs the entire 12mb source to the terminal as it comes across. Disabling logging seems to significantly improve performance (though there are probably still things we can do).

**Comment by jasonLaster** [comment]
Nice point.
