### ISSUE TITLE
CodeMirror line numbers are not aligned

### ISSUE THREAD

**Issue by jlongster** [jlongster/debugger.html#194]
<img width="396" alt="screen shot 2016-05-24 at 9 56 52 am" src="https://cloud.githubusercontent.com/assets/17031/15506519/f5e2eca0-2195-11e6-9611-07618efab1fc.png">

**Comment by helenvholmes** [comment]
Seems to only be happening on James' computer that we know of, not mine or @jasonLaster's. 😖

**Comment by jlongster** [comment]
This was fixed in https://github.com/jlongster/debugger.html/pull/225. The gutters weren't using the monospaced font, and I was getting a different variable-width font that wasn't aligned. Forcing it to the same font as the line fixed it.
