### ISSUE TITLE
static linters

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#20]
- [x] CSS linter
    Run on all pull requests

    

- [x] JS Linter
    Run on all pull requests

    

- [x] Setup Travis CI for linting

**Comment by clarkbw** [comment]
#24 is handling this issue

**Comment by jasonLaster** [comment]
Need to remove the 'use-static' rule change.

**Comment by jlongster** [comment]
This was finished in https://github.com/jlongster/debugger.html/commit/45c68a84d2f0cdce5da76be4a53ad7b84b57a809 right?

**Comment by clarkbw** [comment]
@jasonLaster this is done, right?

**Comment by jlongster** [comment]
Marking this as done. We've been using linters for a while.
