### ISSUE TITLE
enforce types on all app state and protocol data

### ISSUE THREAD

**Issue by jlongster** [jlongster/debugger.html#202]
We're at a point where data is moving around from and to many different places. A common source of errors are simple type errors: objects are not of the right shape and stuff like that. It would be nice to think about how we can better enforce structure of the data.

This is related to #172, but after thinking about it, the app state is rarely the source of problems. This is because the app state generally is well-isolated: the reducers construct it and the selectors deconstruct it. There are pieces of the app state which we should type, but generally those pieces come from other places (for example, the "pause" packet that is saved into the app state).

I'm more interested in enforcing types on all of the data that flows into actions, for example. We would type pieces of the app state before the reducers actually put it in.

What made me think of this is that we are now creating "generic" protocol packets, and it's really hard to make sure that clients are conforming to this protocol. The protocol speaks to the system through redux actions, so if we typed all of the parameters to actions, that seems like it would go a long way.

I'm rambling, but here are several libraries for dynamically checking JS objects:

* union-type https://github.com/paldepind/union-type
* api-check https://www.npmjs.com/package/api-check
* joi https://github.com/hapijs/joi
* tcomb https://github.com/gcanti/tcomb

Out of all of these, I think I prefer tcomb. I've heard of it the most, it supports a "production" mode where it skips typing (so we'd only affect perf in development), and seems well-thought-out.

I'm not entirely sure how this will play with immutable.js, but that's another reason why I'm interested in typing action parameters instead of the app state itself: we never pass immutable objects to actions, so we don't need to type them. All of this is focusing on the protocol packets and making sure we're getting the right data. We might be able to extend this to the app state and implement immutable types as well, but we'll need to try it and see.

**Comment by jlongster** [comment]
Liking this so far, with tcomb we're able to type the entire protocol data:

```js
const t = require("tcomb");

const Source = t.struct({
  id: t.String,
  url: t.String
});

const Location = t.struct({
  sourceId: t.String,
  line: t.Number,
  column: t.Number
});

const Frame = t.struct({
  id: t.String,
  displayName: t.String,
  location: Location
});
```

The only problem I hit is that immutable's default `fromJS` doesn't convert these objects anymore, but writing our own `fromJS` is super easy. A bonus: I might be able to automatically generate immutable `[records](https://facebook.github.io/immutable-js/docs/#/Record)` from these as well so we can just access them like `frame.displayName`.

**Comment by jasonLaster** [comment]
This looks nice.

I like typing the action boundaries.

Was just going to ask if these compose nicely, and then I saw the Location example again.

Keep going

**Comment by jlongster** [comment]
So, yeah this is working out really well so far. I love tcomb's API. I agree: we'll most likely end up with a `types` folder that lays out all of our types.

After working with this, I realized that we really do want to apply the types in many places. For example, we have a `Location` type, and we should apply that in the protocol, the app state, and React components (prop types). But this is hard because all 3 of those are different: protocol uses normal JS objects, app state is immutable, and React has its own prop types.

I played around with typing immutable.js objects with tcomb and it worked surprisingly well: https://gist.github.com/jlongster/3010fd2976f8ace4d4378c296b099a1d. We also just need to figure out how to export a React prop type, and we can use our types everywhere.

I'm not going to go too far with this right now, but this makes me feel confident about being able to extend tcomb later when we want to type our app state as well.

**Comment by jlongster** [comment]
Another *big* benefit that we get from typing all the state is that we will rarely use `fromJS` anymore. The types know how to "hydrate" themselves, meaning that can take an ordinary JS object and recursively convert it to the appropriate types automatically. If we pull off integrating immutable.js with tcomb (which my experiment validates), we'll get automatic conversion from JS->immutable where necessary.

This solves my biggest worry about our app state: mixing immutable and non-immutable values. Our types will solve all the ambiguities.

**Comment by gcanti** [comment]
@jlongster I noticed that you are using `t.struct`. If you don't plan to attach methods to those `struct`s, you may want to replace `struct`s with `interface`s:

```js
const Location = t.interface({
  sourceId: t.String,
  line: t.Number,
  column: t.maybe(t.Number)
}, "Location");
```

the main benefit being that `interface`s don't build new instances (e.g. `Location` in production mode will be an identity function https://github.com/gcanti/tcomb/blob/master/lib/interface.js#L49) so they should be more performant.

**Comment by jasonLaster** [comment]
Thanks @gcanti

**Comment by jlongster** [comment]
@gcanti Interesting, thanks! I will look into that. I'll be working on this today.

**Comment by gcanti** [comment]
@jlongster for any doubt or clarification, feel free to contact me or write here, I'll be to be glad to be of some help

**Comment by jlongster** [comment]
I'll have something soon and would love to have you look over it. Thanks!

**Comment by jlongster** [comment]
@gcanti This is where I ended up: https://github.com/jlongster/tcomb-immutable-experiment

Unfortunately, I need to make sure that immutable.js' API always returns typed objects. This actually wasn't as hard as I thought, but there are holes. For example, `mergeIn` does not work with maps where it automatically created nested maps.

It was a successful experiment though, and I'm going to play with Flow right now. Not sure where we will land.

**Comment by jlongster** [comment]
See #308 for a continuation of this issue. We've decided to give Flow and try, and while we haven't converted everything over yet, we will do so in increments. tcomb still exists in the tree but we will remove it soon. I think we have a good story for typing everything, including the app state.
