### ISSUE TITLE
Selecting a call stack frame should highlight the file in the source tree

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#204]
Steps:
+ Pause
+ select a frame in the call stack in a different file

Notice the source tree still has the other file selected

---

We probably dont have the ability to expand to a file in the tree...

**Comment by jlongster** [comment]
FWIW Chrome does not do this. If we are mimicking "tab" functionality, showing a source just opens a new tab but by default does not touch the tree. It's similar to other editors as well that don't automatically move around the tree. We should have an option for "open in tree" though.

I'm fine if we want to do this now, though, until we actually have tabs.

**Comment by jasonLaster** [comment]
Oh interesting. I'll close the issuer and later we can open a new issue for "reveal in tree" or something like that
