### ISSUE TITLE
Add center landing section

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#208]
Currently, when the debugger opens the Editor is shown with "...". 

![screen shot 2016-05-31 at 3 47 33 pm](https://cloud.githubusercontent.com/assets/254562/15688164/afdd00c2-2746-11e6-8a7d-d8a6ce2b56c8.png)

The designs show a landing section that prompts users to search for a file. 

![screen shot 2016-05-31 at 3 48 01 pm](https://cloud.githubusercontent.com/assets/254562/15688161/a9afb1c2-2746-11e6-9dec-4be71a3343cd.png)

We haven't added a file search UI yet so Cmd + P does not do anything. So we shouldn't show that copy, but everything else makes sense. e.g

+ grey background main panel
+ empty tab bar

**Comment by wldcordeiro** [comment]
I'll take this. 👍 Got some questions, could I contact one of you on irc today for a bit @jasonLaster or @jlongster? Pretty straightforward though.

**Comment by jlongster** [comment]
Feel free to ping me tomorrow!
