### ISSUE TITLE
consolidate selectedSource and selectedSourceOpts

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#209]
Currently we store the selected source in its own field and other options like line and column separately.

This creates some inconsistencies, which we could clean up by keeping the source id and other options in selected source and accessing the source from the store when we need it. 

This will also make selectedSource more similar to other types like location which only store the source id.

This diff walks through the patch that would be necessary
[diff](https://gist.github.com/36937a0c6da5ebe752a724d811b2d990)

**Comment by jlongster** [comment]
I'm not sure about this. `selectedSource` sounds like it's the source object (that should have id and other properties). The `selectedSourceOpts` is basically editor state, so maybe we should just rename it.

**Comment by jasonLaster** [comment]
Yeah, I was thinking about this as well. 

We might want to rename `selectedSource` to `selection` or `selected`

The pain point came last night when i was pairing with another person and he got tripped up on `selectedSourceOpts` and `selectedSource` and it seemed like this could be simplified.

**Comment by jlongster** [comment]
It would help your argument if you explained what he was trying to do and what he was confused by. I think you're right, but hearing more about that would be good.

**Comment by jlongster** [comment]
Because the downside is that the selected source is used very frequently, especially in tests, so it's nice that's it's a first-class part of the app state. I look for it when debugging and logging the app state, etc.

**Comment by jasonLaster** [comment]
I believe this was fixed recently
