### ISSUE TITLE
sources with file:// urls not working

### ISSUE THREAD

**Issue by TatumCreative** [jlongster/debugger.html#214]
Not sure what the issue is, but the debugger doesn't through an error, and remains blank with no sources loaded in.

**Comment by jasonLaster** [comment]
Mind sharing a test file?

**Comment by jlongster** [comment]
I noticed this before at one point, it's probably out URL parsing. Should be easy to reproduce.

**Comment by TatumCreative** [comment]
@jasonLaster http://gregtatum.com/tmp/sources.zip

**Comment by jlongster** [comment]
This will be fixed with node integration, which requires file:// support. https://github.com/jlongster/debugger.html/pull/236
