### ISSUE TITLE
Fixtures are stale

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#226]
The fixture data we are using is out of date. This is not a surprise as we have added features and changed the reducers quite a bit.

The stale fixtures are breaking storybook and will also break component unit tests that we write.

I'll try and write a small script for updating the fixtures so that we can automate this going forward.

**Comment by clarkbw** [comment]
Looks like this work is taking place in #234

**Comment by jasonLaster** [comment]
Yup. It's basically done
