### ISSUE TITLE
add docs about node

### ISSUE THREAD

**Issue by jlongster** [jlongster/debugger.html#239]
Latest node allows you pass a flag in to start the debugging server. We should document how to get a debugger up and running with a node app.

**Comment by clarkbw** [comment]
Yep, I'd say we need some instructions on getting Node installed / updated to a recent version like 6.3.0 that includes the `inspect` option.

Something like:
```
$ brew update
$ brew install node (or brew upgrade node)
$ node --version
$ 6.3.0
```

If upgrading node is an issue possibly include using `nvm` (node version manager)
```
$ brew install nvm
$ nvm install v6.3.0
```

Then instructions for running node with inspect turned on:
```
$ node --inspect server.js
```

**Comment by jasonLaster** [comment]
This looks good. Maybe add a step about selecting the node process from the tabs page.

**Comment by clarkbw** [comment]
I'll take this, I'm going to land the first version of #352 soon which should cover these details.

**Comment by jasonLaster** [comment]
Thanks @clarkbw

**Comment by clarkbw** [comment]
I didn't include the node install instructions because it seemed superfluous
[CONTRIBUTING#nodejs](./CONTRIBUTING.md#nodejs)
