### ISSUE TITLE
Editor breakpoints are missing when the debuggee is refreshed

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#245]
Steps:
1. add breakpoints
2. refresh debuggee

The breakpoints show up in the list, but are not shown in the editor

**Comment by jlongster** [comment]
This bug is for the server. The server does not maintain breakpoints across debugging sessions, and we cannot approximate that from the client because if we try to re-set them on refresh there are breakpoints that will definitely be missed because the code has already executed.

**Comment by jasonLaster** [comment]
Fixed.
