### ISSUE TITLE
Toggling Breakpoints fails

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#247]
Enabling a breakpoint in the breakpoint list throws an error.

**Comment by jlongster** [comment]
I can't repro. This uses to happen, are you sure you're using the latest version? Please test it with all the latest fixes :) Or maybe it's happening in a certain context, which we need more info about.

**Comment by jlongster** [comment]
Closing as I can't repro and I think you were using older code.

**Comment by jasonLaster** [comment]
Thanks. Meant to close. The integration tests now test this as well.
