### ISSUE TITLE
Right sidebar no longer scrolls

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#294]
The right sidebar no longer scrolls. This is clear when the call stack and scopes are expanded.

@jlongster any insights?

**Comment by jlongster** [comment]
That's my fault. I forced the scopes to never wrap and broke the scrolling in that work. I'll fix it asap. I thought it was still scrolling but some of my last-minute changes must have broken it.

**Comment by jasonLaster** [comment]
no worries - thanks
