### ISSUE TITLE
Use Flow to manage types

### ISSUE THREAD

**Issue by jlongster** [jlongster/debugger.html#308]
This might be a little controversial, but after doing a lot of research in #202 about enforcing runtime types in several places of the system, I've come to the conclusion that it's just too messy to mix together immutable, tcomb, and react proptypes. It's certainly doable, but there is a lot of processing going on to integrate types everywhere. I published my work on applying tcomb types to immutable here: https://github.com/jlongster/tcomb-immutable-experiment There are a lot of places that could be bad performance though, either copying data or munging object shapes a lot (which can kill the JIT). It's just a lot of complicated code.

Worse, there are still bugs. I have to wrap immutable's API to make it always return a typed object, but it's really hard to do that some places, so functions like `mergeIn` just don't work. You'll get back Map's with `undefined` values instead of valid values.

When I suggested Flow, Jason encouraged me to look into it, so I've been doing that for the past day or so. I have to say it's been great so far. It's far less work then what I was doing before, and we get much more pervasive type checking. We can type check all function calls even. The app state is type checked. React props can use this. And there's no runtime perf hit.

I'll be opening some PRs to start merging this in. The best part is that flow works really well as a gradual type system, so we only need to type-check small parts at first. It'll completely ignore parts of the file that it can't infer, instead of erroring, and it has commands for showing which parts are validly typed.

**Comment by jlongster** [comment]
Most people's concerns with Flow is that it doesn't work on Windows, but the have tests running on windows (see the badge in the [readme](https://github.com/facebook/flow/blob/master/README.md)) and are going to announce official Windows support very soon.

**Comment by clarkbw** [comment]
As we discussed, flow could present a problem for new contributors.  However we believe that flow is actually fairly easy to read and understand as the typing only creates greater clarity.  Writing in flow is not much more difficult than standard JavaScript and given the benefits of a type checking system (which we desire) where flow seems the best suited we have decided to move forward with this system. 

For future contributors we should strive to make sure that the tooling is just as simple as it is now.  Assuming commands like `npm start` continue to trans-pile code in the background I don't think we'll be adding any undo burden to contributors internal and external.  

We should certainly followup this change with improved documentation that links to the excellent flow docs and quick snippets of how to write in flow.

One last thing worth considering is if other devtools.html projects are going to use flow as well.  Being the only project to use flow could make things difficult for contributors internal and external.  However if something like the console.html project also used flow I think that would be more than enough to tip the scales of momentum in our favor.

**Comment by jlongster** [comment]
Long-term, we should definitely be in sync with other tools and either all or none using flow. I agree that's important. For the next month or so, I would consider our Flow usage experimental and learn enough to be able to decide whether to try and convince the team to use it or not. It's worth noting that it would be very easy to remove Flow: the remove all type annotations (and there aren't very many thanks to its inference system).

**Comment by clarkbw** [comment]
This work is being tracked in #325

**Comment by jlongster** [comment]
#325 has been merged. Flow is integrated into our workflow and we can introduce types where we want.
