### ISSUE TITLE
Add sourceMapUrl to source actor

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#312]

**Comment by jasonLaster** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1286390

**Comment by clarkbw** [comment]
Here's what needs to get done:
- [x] Bug filed
- [x] Needs Patch
- [x] Need Patch Reviewed
- [ ] Try Build
- [ ] Check into m-c
- [ ] Request uplift to Beta

**Comment by jasonLaster** [comment]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=b4f145898118

**Comment by jasonLaster** [comment]
waiting to uplift to beta

**Comment by clarkbw** [comment]
> waiting to uplift to beta

might want to check in on aurora again as it looks like beta isn't in the cards
