### ISSUE TITLE
Investigate translation of strings

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#316]
Aha Card: https://mozilla.aha.io/features/DEBUGX-57

Look into how we would go about handling translations for the strings in the code.

Worth noting that the remote-newtab team was using `react-intl`
https://github.com/mozilla/remote-newtab/search?utf8=%E2%9C%93&q=react-intl
https://github.com/yahoo/react-intl

**Comment by jasonLaster** [comment]
We discussed in channel having a `translate` function which in development is a no-op, but in the toolbox uses `l10n`.

We can test this technique when we have a bundle.
