### ISSUE TITLE
Source Maps - domains are not set

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#328]
domain should be `webpack` but is empty.

Also - the domain should be url decoded  so %20 is a space. See second domain

![screen shot 2016-07-14 at 10 56 57 am](https://cloud.githubusercontent.com/assets/254562/16844084/b3f55460-49b1-11e6-9170-827028833f96.png)

**Comment by jasonLaster** [comment]
@jbhoosreddy want to take a look at this?

**Comment by jbhoosreddy** [comment]
@jasonLaster. Yes. I'd like to.

**Comment by jlongster** [comment]
This was fixed in #393
