### ISSUE TITLE
Chrome - show scopes pane

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#347]
We should add the scopes pane in chrome so that chrome remains at parity.

**Comment by linclark** [comment]
This is something that we have marked as a need-to-have for the console too.

Do you have thoughts on how to display values for the RemoteObjects that are coming in? The Rep system is hardcoded to expect a grip structure, but can be extended to include Reps to handle Chrome RemoteObject structures.

**Comment by jlongster** [comment]
@linclark I haven't looked at how Rep's handles grips, but theoretically it doesn't do too much. It just uses the "preview" object that a grip has, which is an object that has a few key/vals from the object already. So we could either move that logic into the `ObjectInspector`, or make a new Rep that handles whatever Chrome has, and hopefully all that does it traverses the structure to get the "preview" object.

I don't really know yet, just thinking off the top of my head. Need to look into it more.

**Comment by jasonLaster** [comment]
I'm closing this for now as it's something that we are *not* going to handle for the next two sprints. We will get back to this after then though
