### ISSUE TITLE
Change util directory to utils

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#350]
The directories are pluralized (actions, tests, etc)

The two exceptions are lib and util. Is there a reason for this? If not, I'd prefer if they were pluralized. (i don't feel strongly though)

I did a quick m-c check and found mostly *utils*
+ gecko/devtools/shared/gcli/source/lib/gcli/util
+ gecko/devtools/client/responsive.html/utils
+ gecko/devtools/client/webconsole/new-console-output/utils
+ gecko/devtools/server/actors/utils

and only lib
* gecko/devtools/shared/gcli/source/lib/gcli
* gecko/devtools/client/projecteditor/lib/stores
* gecko/devtools/client/projecteditor/lib/plugins
* gecko/devtools/client/projecteditor/lib/helpers
...

given that, i'd suggest changing util to utils and leaving lib the way it is. as it is util is used internally a lot more

**Comment by jlongster** [comment]
"lib" is a very common term (many projects have src/lib/dist/etc dirs) so I agree that we shouldn't change that. I'm fine switching to "utils" though. Eventually we will consolidate them somehow anyway when we don't have the devtools/devtools-sham stuff going on.

**Comment by jasonLaster** [comment]
Here's an example for changing util to utils
https://gist.github.com/7f62e6dc854c5ac0ec7088c85a172b17

There are several other files in the util directory that will need to be mapped as well

**Comment by jbhoosreddy** [comment]
This will be very helpful. Thanks!
