### ISSUE TITLE
Add a public/js/feature.js

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#351]
Feature checking will be something we do in the debugger and debugger related utilities (development-server).

It seems bad to require feature.js in the debugger context when it is outside of public/js.

Given that, i'd suggest we add a feature.js file inside public/js that references config/feature.js and re-exports many of the fields... Down the line, there might also be some differentiation between debugger and tooling feature flagging.

Also, it's worth pointing out that nconf, ... make sense more for building the config blog and less for checking if a feature is enabled.

**Comment by jlongster** [comment]
This makes sense to me. I see feature flags and config as very different things anyway. Usually the feature flags exist only client-side to disable or enable features, and config is used heavily by the server just for parameterization (client can use it too). Basically, feature flags are just booleans for the client-side, and could be specified separately than config.

It's also common to turn on/off feature flags depending on feature detection, while config is just a simple thing to read from json files.

Anyway, all that to say I think this makes sense. We could still use nconf for config, as feature flags are sort of a different thing.

**Comment by jasonLaster** [comment]
Here's a sketch of what it will look like
https://gist.github.com/4f7a079d075c9d619b59f541c36b109b

there are lots of files that use feature.js that need to have their require's remapped

**Comment by jbhoosreddy** [comment]
Thanks for this. I'll look at it now.
