### ISSUE TITLE
Dark Theme / Firebug Theme

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#357]
It would be great to support Dark and Light themes when we launch the new debugger. Here is a screenshot of the current debugger's dark theme.

![screen shot 2016-07-18 at 9 53 25 pm](https://cloud.githubusercontent.com/assets/254562/16936051/f2469eb2-4d31-11e6-9fe6-0dc20995910a.png)

### How to get started

+ The debugger's color's are set with these [variables](https://github.com/jlongster/debugger.html/blob/master/public/js/lib/variables.css).
+ The theme is set in [app.js](https://github.com/jlongster/debugger.html/blob/master/public/js/components/App.js#L108)
+ the current devtools variables are defined [here](https://dxr.mozilla.org/mozilla-central/source/devtools/client/themes/variables.css)
+ It should be possible to write a selector in variables.css for :root and .dark-theme
+ don't worry about toggling between the two themes with ui. It's sufficient to have a PR that add's the css variables and makes sure that the UI looks good. We will figureout how to toggle themes later :)

**Comment by jaideepcoder** [comment]
@jasonLaster I was late to request for the other issue that you suggested. But this looks really interesting. Plus, delving into the CSS should allow me to easily delve into the app. Can I take this issue?

**Comment by jasonLaster** [comment]
@jbhoosreddy thanks. We'll find some more tickets for you soon as well

**Comment by jasonLaster** [comment]
@jbhoosreddy pushed the themes work. We now need to go in and update the CSS so that the two themes look good
