### ISSUE TITLE
Pretty Print Source

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#368]
Pretty print allows  a developer to view a formatted version of the file.  For any files that are minified or poorly formatted this option creates a readable version and because it creates new lines it allows for breakpoints to be added where they weren't easily added before.

- [ ] button to turn on pretty print, likely located in the bottom bar 
- [ ] possibly need a progress bar (may need to file separate issue for this)

I've seen @helenvholmes designs for this bug I can't find them right now. 😭 

Chrome opens a new tab with the `:formatted` version of the file.  In general I like this approach because it is additive.  However it is a little confusing how to get back to this file.  Perhaps there should be an alternate formatted version in the file tree as well?  Not a problem we need to solve right away.

Firefox currently doesn't give access to both source versions at the same time, instead it replaces the existing source file with the formatted version.  If we agree that having a separate version is a good plan, and I think it is, perhaps we look to solve this issue later and just allow Firefox to do what it does for now.

For now we should go with just the manual approach for now, nothing fancy that recognizes the need for pretty print and offers it.  We can do follow up issues for that later.

**Comment by jbhoosreddy** [comment]
I can start looking into this one tonight.

**Comment by helenvholmes** [comment]
I think we're just doing a small icon in the bottom-right—the designs I have for this are attached.

<img width="1081" alt="screen shot 2016-07-21 at 7 58 06 am" src="https://cloud.githubusercontent.com/assets/1720093/17025405/ec3aac96-4f18-11e6-9fe5-f7e5bee4c494.png">

The svg you'll need is here: https://cl.ly/3M16252U2t1s

**Comment by jbhoosreddy** [comment]
After discussing with @jasonLaster, I'm going to drop this one for now.

**Comment by jasonLaster** [comment]
Broke this into four pieces

- [ ] pretty print the source
- [ ] show the pretty print source
- [ ] add / remove breakpoints from the pretty source (probably get it for free)
- [ ] handle cases where the ugly source is source mapped

there's a PR for 1 now, the rest will be done next week. 1 was the hard one.

**Comment by jasonLaster** [comment]
Found a couple of tweaks that will need to be made after this lands:

- [ ] formatted source should not be in the tree
- [ ] pretty print button should be "selected" in pretty source
- [ ] selecting the pretty print button should take you to the other source ugly -> pretty, pretty -> ugly

**Comment by jasonLaster** [comment]
There are several small pieces that still remain. But the happy case has landed and the other work is in small issues, so closing this issue
