### ISSUE TITLE
Pretty Print: Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by darkwing** [jlongster/debugger.html#383]
Comes from:  codemirror.js:8551

Seeing this every time I try to PrettyPrint a JavaScript file

**Comment by jasonLaster** [comment]
Thanks @darkwing. Ignore that for now, I think we'll have to move pretty printing to the client, so this will change pretty significantly

**Comment by jasonLaster** [comment]
fixed now that we're Pretty Printing in the client
