### ISSUE TITLE
Respond to Pause / Resume events

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#44]
**User Stories**

As a web developer, when my code hits a break point I would like to see an indication of which breakpoint was triggered and in which files such that I can inspect the code at that location.

- [x] Highlight the line in the editor

- [x] Toggle the pause / resume button
    Se the pause / resume button to the appropriate state of the debugger.

    

- [ ] Indicate in breakpoint list
    In&nbsp;the global list of breakpoints indicate which breakpoint caused the debugger to pause, if a breakpoint is responsible for the event.

    

- [x] Open the file with the active breakpoint
    Open the&nbsp;file in the Editor that has a breakpoint that was hit.

**Comment by jasonLaster** [comment]
We're getting close. 

Scrolling on a pause event works in firefox, but not in chrome because the editor height is screwy in chrome. (being addressed in #63)

**Comment by jasonLaster** [comment]
done
