### ISSUE TITLE
Step buttons

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#45]
**User Stories**

As a web developer whose code has paused in the debugger I need to be able to step into the next statement&nbsp;on the line that is currently paused such that I go deeper into the stack.

As a web developer whose code has paused in the debugger I need to be able to step out of the current scope I'm paused in such that when I discover I'm in the wrong place I can pop back up the stack.

As a web developer whose code has paused in the debugger I need to be able to step over the function calls on the currently paused line such that I don't jump deeper in the stack and continue to the next statement.

**Notes**

Standard debugger type buttons that trigger their respective action.

Step In

Step Out

Step Over

- [x] Step In button
    Steps into the next function

    

- [x] Step out button
    Steps out of the current scope

    

- [x] Step over button
    Steps over the next function / scope

**Comment by jasonLaster** [comment]
#66 will address this

**Comment by clarkbw** [comment]
Done!
