### ISSUE TITLE
Pause / Resume button

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#46]
**User Stories**

As a web developer I want to be able to resume the debugger which has paused at a breakpoint such that I can continue watching the code run.

As a web developer I want to be able to pause the debugger such that I can trigger an action and immediately see what code is run first.

- [x] Pause / Resume button
    A pause / resume&nbsp;button that toggles the debugger between the two possible states.

**Comment by jasonLaster** [comment]
Started looking into this [patch](https://gist.github.com/jasonLaster/7220a6fea9adfe697b54f02aa29f6418). Adding a pause button that breaks on next execution is easy.

What we need to figureout before we start is how we are going to maintain paused state:
1. willPause
2. paused => location of pause, why...

**Comment by jasonLaster** [comment]
I believe this one is done
