### ISSUE TITLE
Update Editor style

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#47]
- [x] Update font styles
    The current font choice is small and could be improved by using a better monospaced option.

    

- [x] Update breakpoint styles
    The breakpoint style could be improved and the line number needs to be visible

    

    [https://github.com/jlongster/debugger.html/pull/85](https://github.com/jlongster/debugger.html/pull/85)

**Comment by jasonLaster** [comment]
It'd also be nice to have the syntax highlighting be consistent.

**Comment by clarkbw** [comment]
Is @helenvholmes going to take this on?

**Comment by jlongster** [comment]
I was going to fix the breakpoint styles in by breakpoint patch, but I'm still rebasing it. I'm not sure about matching the current syntax highlighting; that might we something we should push off to a later sprint.

**Comment by clarkbw** [comment]
> matching the current syntax highlighting

Ok, lets bump this out for now.

**Comment by jasonLaster** [comment]
> breakpoint styles
There's a PR for it

> syntax highlighting 
Helen is updating gecko DevTools colors now and will be able to do this after that.

**Comment by clarkbw** [comment]
Ok, #85 is handling the break point styles.
I've put the syntax highlighting into a separate card in the Aha backlog
