### ISSUE TITLE
CSS Pane / Splitter Component needs to be  improved

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#48]
The Pane / Splitter Component needs to be made more robust in terms of CSS to prevent things like over expansion from child content.

- [ ] Prevent child content from expanding the pane size

**Comment by jasonLaster** [comment]
@jlongster did your splitter work last friday fix this?

**Comment by jlongster** [comment]
Yes, it definitely should have. The panes should be much more stable now since 1f39e0fd27f245ce4cb699243c1636fcd322c873
