### ISSUE TITLE
Investigate Travis CI for running tests

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#50]
We want Travis to run tests against every PR however currently it is only running lint tests.

In order to run our unit tests we need the xpcshell binary available on Travis.

There are several ways to possibly accomplish this:

- Download an xpcshell binary (that matches platform) from somewhere and use this to run test
- Build Firefox from source to create the xpcshell binary to run the tests
- Pull a copy of xpcshell into our own repo which could run the tests for us

**Comment by clarkbw** [comment]
Ok, here's what I've found.

From a URL like this: 
https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/

You could download an SDK build like this:
https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-48.0a1.en-US.linux-i686.sdk.tar.bz2

In that build you'd find xpcshell under `sdk/bin/xpcshell`.  I don't know if it is exactly what we're looking for but it seems pretty close.  I'm going to try a test build and then maybe a test Travis build.

**Comment by jasonLaster** [comment]
Awesome @clarkbw.

**Comment by jlongster** [comment]
@clarkbw neat! that might work. we would need to point the runner to that whole "obj dir" so it can find all the dynamic libraries it needs, but I assume they are all there because regular Firefox needs them too. 

The last bit would be how to get the `head.js` file from the source, which is what we use the "src dir" option for, but if that's really the last piece we can just copy that in and commit it.

**Comment by clarkbw** [comment]
> we would need to point the runner to that whole "obj dir" so it can find all the dynamic libraries it needs

Ah, that is making sense.  I don't know how to run the `xpcshell` command so I'm just getting this error.  But I think we're on the right track here.

```
$ ./run-mozilla.sh ./xpcshell
dyld: Library not loaded: @executable_path/libnss3.dylib
  Referenced from: /Users/clarkbw/Downloads/mac-fx-sdk/sdk/bin/xpcshell
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by clarkbw** [comment]
Closing this out now that #60 has landed and we're going away from xpcshell.
