### ISSUE TITLE
Write up a CONTRIBUTING.md doc

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#51]
Set clear expectations and guidelines for contributing.

- [ ] Github Quick Replies
    Explaining how we are moving fast etc.

    

- [ ] Link to Contributing doc from the README

**Comment by helenvholmes** [comment]
@clarkbw, do you think this will get completed by the demo? (I suspect people will want to contribute after seeing the demo, it'd be great to have a contributing doc by then.)

**Comment by jasonLaster** [comment]
Added!
