### ISSUE TITLE
Toggling breakpoints in global list

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#52]
**User Stories**

As a web developer I need to be able to toggle breakpoints in other areas of code that aren't visible in the debugger editor such that I can avoid hitting breakpoints I'm not currently interested in.

- [x] Add checkbox to each breakpoint in the global list
    Checked status of checkbox should be wired up to the enabled / disabled status of the breakpoint.

**Comment by jlongster** [comment]
This will be fixed in https://github.com/jlongster/debugger.html/pull/94
