### ISSUE TITLE
Sources Style Pass

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#53]
The Sources Pane is now selectable and grouped by domain. 

![](http://g.recordit.co/96EsWgjRod.gif)

It'd be great to do a quick style pass on typography and layout. Hopefully we will be able to add nesting/collapsing with a tree view soon, and do a second pass.

![screen shot 2016-04-12 at 4 08 25 pm](https://cloud.githubusercontent.com/assets/254562/14473985/c0f6013c-00c8-11e6-8fa7-a71d3f0f321d.png)

**Comment by jlongster** [comment]
This has been fixed, and we are looking into a tree view next
