### ISSUE TITLE
Add a dev/prod flag

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#55]
The flag will help with asserts, logging, and other tools that should only run in dev.

**Comment by jlongster** [comment]
We could put this in `environment.json`, and on startup we set `AppConstants.DEBUG_JS_MODULES`  to that value. That flag will turn on all the stuff inside ff-devtools-libs like asserts.

**Comment by jasonLaster** [comment]
this is being handled elsewehere
