### ISSUE TITLE
Fix editor scrolling in Chrome

### ISSUE THREAD

**Issue by jlongster** [jlongster/debugger.html#63]
For some reason it doesn't scroll right now. Works fine in Firefox. It's probably a simple CSS fix (`overflow: auto` somewhere).

**Comment by jasonLaster** [comment]
this might address some of the firefox, chrome inconsistencies
http://stackoverflow.com/questions/33636796/webkit-not-filling-the-100-height-of-a-flex-parent

**Comment by jasonLaster** [comment]
Actually, not fixed yet

**Comment by jasonLaster** [comment]
This comment offered a solution/hack around a codemirror parent / grandparent https://github.com/codemirror/CodeMirror/issues/3679#issuecomment-171533964

**Comment by jasonLaster** [comment]
Fixed! Yessssss
