### ISSUE TITLE
Chrome DevTools crashes

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#67]
So, this is a little ironic, and mostly sad, but when I'm debugging debugger.html in Chrome, chome devtools is very unreliable. I'd like to get to the bottom of this, I'm not sure if it's a websocket thing, webpack source map thing, or what, but it makes it very difficult to make progress.

**Comment by jasonLaster** [comment]
[chrome devtools](http://recordit.co/7kfHddzTUl) crash.

Steps to reproduce:
1. add a breakpoint in [thunk-middleware](https://github.com/jlongster/debugger.html/blob/master/js/util/thunk-middleware.js#L15) 
2. select a source, which is an async action that invokes an async action
3. step into the second async action call. Chrome DevTools will crash accessing the threadClient property in the function params

**Comment by jlongster** [comment]
... have you tried Firefox? Use our devtools :)

**Comment by jasonLaster** [comment]
@jlongster Firefox devtools work beautifully here.

Here's a *fix* 
https://gist.github.com/1f18b7fb5882cb0635596dd3651cb862

I bet it's a bug on how devtools handles stepping with these object accessors. Will file a crbug

**Comment by jlongster** [comment]
I'd really rather not make our code uglier to cater to Chrome's devtools. :)

**Comment by jasonLaster** [comment]
This was addressed with a babel plugin for function params
