### ISSUE TITLE
Consider keeping deps up-to-date with greenkeeper.io

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#79]
Greenkeeper is popular with other major open source projects.  I've used greenkeeper my own projects and find it really useful.  It takes the work out of tracking package dependencies by auto-monitoring them and bringing them to our attention as needed. 

> Greenkeeper sits between npm and GitHub, observing all of the modules you depend on. When they get updated, your project gets a pull request with that update. Your CI tests kick in, and Greenkeeper watches them to see whether they pass. If they do, you can just click the merge button, and we'll even auto-close branches for older versions for you. If not, you can use the branch to fix things.

https://greenkeeper.io/#how-it-works

@jlongster is the admin so he will have to enable this if we want it.  

Here's an example of what it will do on the first run: clarkbw/debugger.html#1

**Comment by jasonLaster** [comment]
Thanks for bringing this up @clarkbw. I'd like to try greenkeeper and see if it helps us.

I've been bitten in the past by stale dependencies and at the very least, this could give us a signal of how we're doing. Also, it's definitely helpful to pay down the dependency debt incrementally before it builds up.

**Comment by jlongster** [comment]
I just enabled it. We'll see how it goes. I worry that it will be too much distraction this early. I wish there was just a simple CLI program that I could run to manually see which things are out-of-date. Many packages don't have security risks and don't really need to be updated frequently.
