### ISSUE TITLE
Align Action Buttons to Pixel Grid

### ISSUE THREAD

**Issue by jasonLaster** [jlongster/debugger.html#86]
Spoke with Helen today, and will do a quick pass on some of our SVG icons 

~~- [ ] make the width / height consistent~~
~~- [ ] set fill states (disabled, hover, active)~~
~~- [ ] convert stroke widths to paths for pixel snapping~~

[@helenvholmes Edits]:
- [x] pause
- [x] play
- [x] step into
- [x] step out
- [x] step over
- [x] remove all breakpoints
- [x] blackbox source
- [x] pretty print

**Comment by jlongster** [comment]
I vote we close this bug and break it up into something more specific to which icons. I know she's going to give up new pause/step icons soon, but it's not clear which icons this issue is talking about.

**Comment by helenvholmes** [comment]
<img width="793" alt="screen shot 2016-05-24 at 3 03 26 pm" src="https://cloud.githubusercontent.com/assets/1720093/15516511/0a86ef46-21c1-11e6-946b-9a2bc453c67e.png">

Since some of the icon work was captured in #196, I'm voting we repurpose this to handle cleaning up the Debugger action icons which are looking a little wonky.

**Comment by jasonLaster** [comment]
@helenvholmes are those debugger icons done and ready to be added? Or do you still need to clean them up before they are added?

**Comment by helenvholmes** [comment]
I unfortunately didn't have tie to work on them yesterday/today—they still need some polish before I add them.

The relevant file is [here](https://www.dropbox.com/s/e1uarq0esre4qjj/Icon-Generator.sketch?dl=0).

**Comment by helenvholmes** [comment]
@jlongster: we'd talked about possibly changing pretty print, correct? Did you have other thoughts on what that could be?

**Comment by jlongster** [comment]
@helenvholmes not that I remember? The only ones I wanted to change was step in and out. They should be the same as our current debugger (the general shape at least). The pretty-print one is fine with me!

**Comment by jasonLaster** [comment]
I like pretty print too

**Comment by helenvholmes** [comment]
Ah, awesome—I have those changed in the branch I'm working on then, rad. Disable (remove?) breakpoints + blackboxing look fine too then?

**Comment by jasonLaster** [comment]
Yay! @helenvholmes looks good.
