### ISSUE TITLE
Investigate Call Stacks

### ISSUE THREAD

**Issue by clarkbw** [jlongster/debugger.html#99]
**User Story**

As a user who has paused the debugger I would like a display of the current frames in the call stack such that I can see the chain of events that brought me to the current code as well as jump from this frame to another to view the source code.

- [x] Selecting a frame opens the source location

- [x] List of all frames in the stack
    Below the break points and above the scope

**Comment by jlongster** [comment]
I will work on this

**Comment by clarkbw** [comment]
#121 has some of this work
